### ISSUE TITLE
NoClassDefFoundError with latest version of intellij 2022.3

### ISSUE THREAD

**Issue by yadavsudhir405** [fehnomenal/intellij-direnv#30]
Hi,

I have recently upgraded intellij version to 2022.3. With better direnv plugin I have been constantly getting below error. Few of the intellij shortcut such as Command + Shift + o(file search) and Command + Shift + A(find all action) not working with this crash. The moment I disable this plugin, Intellij starts working fine as in shortcuts for file search and find all actions.

This error occurs when I try to use shortcut for file search or find all action.

Intellij Version: 2022.3(latest) mac version
Plugin version: 1.0.0

java.lang.NoClassDefFoundError: com/intellij/sh/SHIcons
	at com.fapiko.jetbrains.plugins.better_direnv.language.filetype.DirenvFileType.getIcon(DirenvFileType.java:38)
	at com.intellij.ide.util.gotoByName.FileTypeRef$Companion.forFileType(LanguageRef.kt:55)
	at com.intellij.ide.util.gotoByName.FileTypeRef$Companion.forAllFileTypes(LanguageRef.kt:61)
	at com.intellij.ide.util.gotoByName.FileTypeRef.forAllFileTypes(LanguageRef.kt)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.createFileTypeFilter(FileSearchEverywhereContributor.java:167)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.<init>(FileSearchEverywhereContributor.java:47)
	at com.intellij.ide.actions.searcheverywhere.RecentFilesSEContributor.<init>(RecentFilesSEContributor.java:31)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.createContributors(SearchEverywhereManagerImpl.java:175)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.show(SearchEverywhereManagerImpl.java:81)
	at com.intellij.ide.actions.SearchEverywhereBaseAction.showInSearchEverywherePopup(SearchEverywhereBaseAction.java:67)
	at com.intellij.ide.actions.GotoActionAction.actionPerformed(GotoActionAction.java:27)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.sh.SHIcons PluginClassLoader(plugin=PluginDescriptor(name=Better Direnv, id=com.fapiko.jetbrains.plugins.better_direnv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/223.7571.182/IntelliJ IDEA.app.plugins/better_direnv, version=1.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=405, state=active)
	... 41 more

**Comment by yadavsudhir405** [comment]
![Screenshot 2022-12-05 at 09 13 29](https://user-images.githubusercontent.com/11731706/205544919-27117ec6-717a-4f15-baa1-9c48f734b85d.png)

**Comment by huyz** [comment]
You're confusing plugins.  You wanted to report here: https://github.com/Fapiko/intellij-better-direnv/issues

**Comment by fehnomenal** [comment]
Yes, closing as wrong repo.

**Comment by yadavsudhir405** [comment]
@huyz  Thanks for pointing out to the right repo.
