### ISSUE TITLE
IntelliJ deprecation warning regarding 'getActionUpdateThread'

### ISSUE THREAD

**Issue by Paladinium** [fehnomenal/intellij-direnv#53]
Using IntelliJ IDEA 2024.1 (Ultimate Edition), the IDE shows an internal error using plugin version 0.2.9:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'systems.fehn.intellijdirenv.DirenvImportAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: systems.fehn.intellijdirenv]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by 1nv0k32** [comment]
Same issue here and it's blocking us. Does someone know how to deal with this?

**Comment by 1nv0k32** [comment]
For more info:
I've got the error on version `0.2.10` of the plugin and Pycharm `2024.1.4` on a Windows machine connected to NixOS on WSL.

Links:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/18697727524754-Deprecation-warning-with-ActionUpdateThread
